services:
  server:
    image: vimukthi01/bus-seat-booking-application:server
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/bus_booking.db:/app/bus_booking.db
    environment:
      - PORT=3000

  client:
    image: vimukthi01/bus-seat-booking-application:client
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
